/**
 * MV3 shuts an extension service worker down after 30s with no events. A field
 * answer generated by a local model runs for minutes with nothing happening in
 * between, so the worker has to be held open explicitly — Chrome's documented
 * fix is a heartbeat that calls a trivial extension API, which resets the idle
 * timer (https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers).
 *
 * The separate 5-minute cap on a single activity is NOT resettable, so this only
 * buys time up to `MAX_ACTIVITY_MS` — callers must time out below that ceiling
 * rather than rely on staying alive indefinitely.
 */

/** Comfortably under the 30s idle timeout the heartbeat exists to reset. */
export const KEEPALIVE_INTERVAL_MS = 20_000;
/** Chrome kills any single activity at 5 minutes; leave headroom under it. */
export const MAX_ACTIVITY_MS = 270_000;

let holders = 0;
let heartbeat: ReturnType<typeof setInterval> | null = null;

function beat(): void {
  void chrome.runtime.getPlatformInfo().catch(() => undefined);
}

/**
 * Holds the service worker open for the duration of `work`. Ref-counted, so
 * concurrent generations (one per form field) share a single heartbeat and the
 * last one to finish stops it.
 */
export async function withKeepAlive<T>(work: () => Promise<T>): Promise<T> {
  if (holders === 0) heartbeat = setInterval(beat, KEEPALIVE_INTERVAL_MS);
  holders += 1;
  try {
    return await work();
  } finally {
    holders -= 1;
    if (holders === 0 && heartbeat !== null) {
      clearInterval(heartbeat);
      heartbeat = null;
    }
  }
}

/** Test seam: how many operations are currently holding the worker open. */
export function keepAliveHolders(): number {
  return holders;
}
